services:
  bot:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - env/main.env

  nginx:
    image: nginx:1.23
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./env/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bot/static:/var/www/app/static  # Пробрасываем статику
    depends_on:
      - bot



